baseURL: 'https://ottan.jp'
languageCode: ja
defaultContentLanguage: ja
publishDir: public
contentDir: content
title: OTTAN.JP
theme: languor
hasCJKLanguage: true
summaryLength: 150
canonifyURLs: true
disqusShortname: ottanxyz
paginate: 20
googleAnalytics: G-YEW10M8DW4
rssLimit: 15
enableGitInfo: true
permalinks:
  posts: /posts/:year/:month/:filename
markup:
  highlight:
    style: github
  goldmark:
    renderer:
      unsafe: true
params:
  author: ottanjp
  favicon: images/favicon.ico
  twitter: 'https://twitter.com/ottanxyz/'
  github: 'https://github.com/ottanjp/'
  rss: 'https://ottan.jp/index.xml'
  description: iPhone、Mac、Windows、ブログに関する様々なTips、トラブルシューティングをご紹介します
  locale: ja_JP
related:
  includeNewer: true
  indices:
  - name: tags
    weight: 100
  threshold: 20
  toLower: false
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
outputs:
  home: [HTML, RSS, Algolia, JSON]
