template: static/card/template.png
title:
  start:
    px: 113
    pY: 252
  fgHexColor: "#FFFFFF"
  fontSize: 96
  fontStyle: Bold
  maxWidth: 1800
  lineSpacing: 10
category:
  start:
    px: 113
    py: 191
  fgHexColor: "#E5B52A"
  fontSize: 42
  fontStyle: Regular
info:
  start:
    px: 0
    py: 0
  fgHexColor: "#212227"
  fontSize: 0
  fontStyle: Regular
tags:
  start:
    px: 120
    py: 700
  fgHexColor: "#FFFFFF"
  bgHexColor: "#7F7776"
  fontSize: 26
  fontStyle: Bold
  boxAlign: Left
  boxSpacing: 6
  boxPadding:
    top: 16
    right: 16
    bottom: 16
    left: 16